### ISSUE TITLE
Sphinx-copybutton takes too much time to load

### ISSUE THREAD

**Issue by wuyisheng** [choldgraf/sphinx-copybutton#15]
It took too much time to load these resources.

```python
fa_url = 'https://use.fontawesome.com/releases/v5.2.0/css/all.css'
boot_css_url = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
boot_js_url = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
pop_js_url = "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
clipboard_js_url = "https://cdn.jsdelivr.net/npm/clipboard@1/dist/clipboard.min.js"
```

Can you put these resources in a static directory?

**Comment by choldgraf** [comment]
hmmm I *think* that these are now removed as dependencies (except for the `clipboard_js_url` library) because...could you double-check you're running the latest version (and if that still doesn't work, can you try w/ the latest "master"?)

**Comment by wuyisheng** [comment]
Emmm...I workaround this problem. I modified `__init__.py` and put these resources in a static directory on my computer.

**Comment by choldgraf** [comment]
I'm a bit confused by this problem - it sounds like you're using an old version of the package...here is the relevant line in the latest version:

https://github.com/choldgraf/sphinx-copybutton/blob/master/sphinx_copybutton/__init__.py#L11

There's only a single resource being loaded, not all of the ones you listed...
