### ISSUE TITLE
Read config from conf.py

### ISSUE THREAD

**Issue by jessetan** [choldgraf/sphinx-copybutton#21]
https://github.com/rtfd/sphinx_rtd_theme/issues/429 mentioned a need to read configuration from conf.py.

You can define configuration values in your `setup()` function by calling [`app.add_config_value()`](http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_config_value)
You can get the value somwehere else using `app.config` (if `app` is available, like from an event callback) or from `self.state.document.settings.env.config` from your extensions `run()` function.
More direct access may be possible, but this works for me.

**Comment by choldgraf** [comment]
very cool - thanks for the information :-)

do you know of an elegant way to pass variables from the python space into the javascript space? I guess you could just add `<script>` code to the built site or something?

**Comment by jessetan** [comment]
You can indeed write a `<script>` element into the page with the variables, or you can use templating in the JS file.
That's the way https://github.com/rtfd/readthedocs-sphinx-ext does it, but you'll have to dig in the code to see how it works

**Comment by choldgraf** [comment]
thanks for the tip! will give this a shot when we start on either

#20 or #9

**Comment by choldgraf** [comment]
I believe this is now implemented!
