### ISSUE TITLE
Load icon from local installation

### ISSUE THREAD

**Issue by xtianus** [choldgraf/sphinx-copybutton#27]
The copy icon is currently loaded from https://gitcdn.xyz/repo/choldgraf/sphinx-copybutton/master/sphinx_copybutton/_static/copy-button.svg

It would be much better to load it from my local installation so that my site doesn't depend on your site being online...

**Comment by choldgraf** [comment]
I'm all for it, just haven't had the cycles to figure it out. PRs definitely welcome to change the behavior to package and load it locally!

**Comment by mgeier** [comment]
See #42 for a possible solution.
