### ISSUE TITLE
Adding fade effect to icon

### ISSUE THREAD

**Issue by xtianus** [choldgraf/sphinx-copybutton#28]
Maybe you'd like to consider adding a fade effect to the copy icon so that it only appears when hovering on the code block.
This should do it:

```
.highlight .copybtn {
	opacity: 0;
	transition: opacity 0.5s;
}
.highlight:hover .copybtn {
	opacity: 1;
}
```

**Comment by choldgraf** [comment]
seems like a reasonable idea to me!
