### ISSUE TITLE
Is sphinx_copybutton safe for parallel reading?

### ISSUE THREAD

**Issue by dstansby** [choldgraf/sphinx-copybutton#33]
Building docs in parallel (`O=-j4` option to sphinx-build) that include `sphinx_copybutton` emits the following warning:
```
WARNING: the sphinx_copybutton extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```
Would it be possible to declare whether sphinx_copybutton is safe for parallel reading to get rid of this warning?

**Comment by choldgraf** [comment]
Hmmm, are you on the latest version? I thought this had been fixed (see https://github.com/choldgraf/sphinx-copybutton/issues/22 and https://github.com/choldgraf/sphinx-copybutton/pull/23)

**Comment by dstansby** [comment]
Sorry, my bad, upgrading solved the issue.

**Comment by choldgraf** [comment]
no worries @dstansby , issues that get closed without me needing to do anything are my favorite issues :-)
