### ISSUE TITLE
PyPI tarball contains a top-level directory `sphinx-copybutton-0.2.5/`

### ISSUE THREAD

**Issue by sandrotosi** [choldgraf/sphinx-copybutton#34]
Hello,
i'm working to package sphinx-copybutton for debian, and noticed how the tarball in PyPI contains a top-level directory named `sphinx-copybutton-0.2.5/` . this is could create troubles down the line when a new release is published, as now the 2 versions will be entirely different.

what's customary to do (and i believe the default behaviour of `python3 setup.py sdist`) is to publish the project files (as-in the files as shown in the GH page) at the top-level.

thanks for considering!

**Comment by choldgraf** [comment]
oops!  hmmm,  I certainly didn't mean to do anything different from the same approach that other projects use, so I'm guessing I just did something wrong :-) do you have a link to instructions that you use when publishing things?

**Comment by choldgraf** [comment]
I just cut a new release using twine instead of flit, does it look correct to you now?

**Comment by sandrotosi** [comment]
apologies, i think i was misusing a command i rarely use to create new packages in Debian. all is good, closing
