### ISSUE TITLE
pypi package name

### ISSUE THREAD

**Issue by NBajanca** [choldgraf/sphinx-copybutton#4]
I was having trouble finding this on pypi because it is ``sphinx_copybutton`` and not ``sphinx-copybutton``.

I would suggest changing either the docs or the package name.

**Comment by choldgraf** [comment]
Good point - I *think* I got this fixed https://github.com/choldgraf/sphinx-copybutton/commit/898f05f86d911ab367c1cab99c94a4e30ab30049 but maybe it'll take some time to propagate on pypi?
