### ISSUE TITLE
_static folder and LICENSE missing from PyPI tarball

### ISSUE THREAD

**Issue by bcbnz** [choldgraf/sphinx-copybutton#40]
In the 0.2.6 tarball on PyPI, both the _static folder and the LICENSE file are missing. They appear to exist in the wheel.

**Comment by choldgraf** [comment]
hrmm - any idea for how this can be fixed?

**Comment by bcbnz** [comment]
The linked pull request fixes it for me -- with it, `python setup.py sdist` created a tarball containing _static and LICENSE.

**Comment by sandrotosi** [comment]
yes, please keep including LICENSE in the released tarball, speaking from a Debian perspective here :)

**Comment by sandrotosi** [comment]
it also looks like the entire `doc/` directory is not missed? please re-add that too

**Comment by choldgraf** [comment]
merged this! thanks, hopefully it's fixed, python packaging is still a mystery to me.

@sandrotosi please do feel free to open a PR if you know the right way to include `doc/` in the resulting tarball!

**Comment by bcbnz** [comment]
@choldgraf I've opened PR #44 which adds a MANIFEST.in telling setuptools to include the `doc/` directory. (Python packaging is something of a mystery to me to, but Google and trial and error says this way works!).

Once you've checked and merged this could you release a new version on PyPI? That way I can get the Arch Linux package up-to-date :).

**Comment by choldgraf** [comment]
looks great, thanks...it might be a bit before I can cut a new release (on holiday until early january) but I'll get to it quickly! Thanks for all of the patches!

**Comment by sandrotosi** [comment]
@choldgraf thanks! just so you know, we are kinda stuck in debian, as we cant update the package until there's a new upstream release with the doc/ directory present, so as soon as you can release it, the better it will be for us :)

**Comment by choldgraf** [comment]
Makes sense - sorry for the slowness, I’m just out of the country on holiday now so have minimal working time. I’d like to get #43 figured out before we cut a new release but that shouldn’t be too much work I think
