### ISSUE TITLE
Include a copy of clipboard.min.js in the distribution?

### ISSUE THREAD

**Issue by mgeier** [choldgraf/sphinx-copybutton#43]
Alternatively, an option for `conf.py` should be provided that allows specifying a local path (similar to [mathjax_path](http://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax_path)).

Otherwise it is not possible to use this extension without internet connection.

See also #15.

**Comment by choldgraf** [comment]
Hmmm - the main reason that I'm loading it from a CDN is because it will generally be faster to load than if somebody is using GitHub pages for a CDN. Are you trying to create documentation that works without the internet? I'm trying to figure out how common this would be...

**Comment by mgeier** [comment]
> the main reason that I'm loading it from a CDN is because it will generally be faster to load than if somebody is using GitHub pages for a CDN.

I'm talking about putting it into the "static" directory, i.e. it would be loaded from the same server as the rest of the HTML/JS/CSS files.
Would this be generally slower than loading it from `cdnjs.cloudflare.com`?

Either way, I'm not sure if it would really make sense to copy the file.

Sphinx itself seems to use both strategies. For example, it loads `jquery.js` and `underscore.js` from the "static" directory (https://github.com/sphinx-doc/sphinx/tree/master/sphinx/themes/basic/static), but when using the `sphinx.ext.mathjax` extension, the JavaScript is per default loaded from `cdnjs.cloudflare.com` (which can be changed with the `mathjax_path` configuration option).

> Are you trying to create documentation that works without the internet?

No, but I'm trying to make it easy for others to do so.

> I'm trying to figure out how common this would be...

One example that comes to mind is when some docs are packaged, for example, in a Debian package. Debian maintainers often like to replace online dependencies with their own local dependencies, and having a configuration option would make that easy.

I guess it also makes a difference in non-public company networks, which probably have a restricted access to the web?

**Comment by choldgraf** [comment]
> Would this be generally slower than loading it from cdnjs.cloudflare.com?

I think it'd depend on where you were hosting it (e.g. github pages vs. netlify would probably have different CDN abilities).

> Sphinx itself seems to use both strategies

hmmm, that's a fair point. Since Sphinx is already doing this anyway, I don't know that we'd gain much from using a separate CDN for the minified JS. 

So I'm +1 on including clipboard.min.js in the bundle w/ Sphinx, and just referring to it statically

**Comment by mgeier** [comment]
OK, cool!

I can make a PR if you want me to, but I don't know if we have to do anything special regarding the license of the file.
Do we have to add a license text somewhere?

Or probably it would be best to include it as `git submodule` and create a symbolic link to the file https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.min.js?

**Comment by mgeier** [comment]
I've added #48 as a possible solution.
