### ISSUE TITLE
Using sphinx-copybutton breaks custom layout

### ISSUE THREAD

**Issue by jhamman** [choldgraf/sphinx-copybutton#5]
First off - very cool package. Thanks for putting it together. 

I tried adding `sphinx-copybutton` to our docs and got some unexpected results. It seems that something in the plugin is messing with the css for our custom bootstrap theme/css.

![image](https://user-images.githubusercontent.com/2443309/46123226-1e460b80-c1d2-11e8-8e8f-065f3d78c2d8.png)
Left: expected layout without `sphinx-copybutton`, Right: layout with `sphinx-copybutton`. 

Do you have thoughts on what might be causing this or how to fix it?

**Comment by choldgraf** [comment]
holy moly!

here's the only CSS that it adds:

https://github.com/choldgraf/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copybutton.css

perhaps we can find the clashes and update the sphinx-copybutton CSS with more specific rules

**Comment by jhamman** [comment]
hmmm, that looks fairly innocuous. Maybe @rabernat has an idea what's going on?

**Comment by choldgraf** [comment]
It could be that it's also adding the HTML element, maybe that's what's breaking things? So not the CSS per se, but the addition of the new element?

**Comment by MacHu-GWU** [comment]
@jhamman Yes, I have similar issue when using bootstrap theme.

**Comment by choldgraf** [comment]
Anybody figure out a fix for this? (e.g. CSS overrides or something?) if so, PRs would be most welcome!

**Comment by jhamman** [comment]
I was not able to find a solution. I've given up for the time being but will track this issue.

**Comment by choldgraf** [comment]
@jhamman could you share a github link w/ a version of the site where S-CB breaks the layout? I can try playing around with it.

**Comment by MacHu-GWU** [comment]
@choldgraf  https://ryan-roemer.github.io/sphinx-bootstrap-theme/
This theme and a lot more's layout are broken

**Comment by choldgraf** [comment]
ahhh I think I see what's going on - SCB is loading bootstrap on its own which is breaking previously-existing bootstrap deployments. I'm working on a fix that'll drastically simplify how SCB is loaded and should solve this problem

**Comment by choldgraf** [comment]
Hey @jhamman and @MacHu-GWU can you try out the latest version from GitHub master? In #6 I think I've fixed the bootstrap layout problem.

**Comment by MacHu-GWU** [comment]
@choldgraf  `sphinx-bootstrap-theme` fixed.

Ha, I see why, https://github.com/choldgraf/sphinx-copybutton/commit/eb1f43138ba964135d9bf9c6a846f184964d7190#diff-2204ca80a3707660cd87ae77bceec515 this change did the trick.

Looks like you overwrite the bootstrap layout with your customize .css and .js CDN. So the bootstrap theme's layout is not properly triggered.

Am I correct?

**Comment by choldgraf** [comment]
@MacHu-GWU hehe yep, the previous approach to loading JS/CSS was just "obliterate everything already there" apparently haha

OK, I'll cut a new release so that others can benefit from the fix!

**Comment by choldgraf** [comment]
Closing this issue for now, though @jhamman if your setup is still broken feel free to re-open!

**Comment by jhamman** [comment]
Thanks @choldgraf for working on this. I wont have a chance to give this a try until tomorrow but please go ahead with the release as planned.

**Comment by jhamman** [comment]
@choldgraf - finally got around to trying this and it seems to be working well. Here's an example for those interested in seeing how it plays: http://pangeo.io/setup_guides/hpc.html 

Thanks again for fixing this.
