### ISSUE TITLE
Add a PyPI badge to your repo homepage

### ISSUE THREAD

**Issue by MacHu-GWU** [choldgraf/sphinx-copybutton#7]
Add this to your README.md file. So people know what is the latest version of your project.
Because I have to refresh your PyPI page to see if you released a new update. And allow people quickly jump to PyPI page.

```
[![PyPI](https://img.shields.io/pypi/v/sphinx-copybutton.svg)](https://pypi.org/project/sphinx_copybutton/)
```

This is how it looks like:

[![PyPI](https://img.shields.io/pypi/v/sphinx-copybutton.svg)](https://pypi.org/project/sphinx_copybutton/)

**Comment by choldgraf** [comment]
Good call! It's in the readme now!
