### ISSUE TITLE
Extension does not work with Sphinx 2.4.4

### ISSUE THREAD

**Issue by tzach** [choldgraf/sphinx-copybutton#70]
I try to move from Sphinx 1.8.x to Sphinx 2.4.4, and in the process sphinx-copybutton stopped working.
I see the following JS error in Chrome console:
```
copybutton.js:69 Uncaught ReferenceError: copybuttonSkipText is not defined
    at copybutton.js:69
    at Array.forEach (<anonymous>)
    at o.copyTargetText [as text] (copybutton.js:68)
    at o.value (clipboard.min.js:7)
    at HTMLBodyElement.<anonymous> (clipboard.min.js:7)
```

**Comment by choldgraf** [comment]
Hmmm - that's a bit strange, I'm using 2.4.4 myself and it has worked fine. Can you try re-installing or upgrading both sphinx-copybutton and sphinx?

**Comment by tzach** [comment]
Sorry, look like the problem is probably related to clipboard manager I'm using.
I will sit in the corner for 15 minutes.
