### ISSUE TITLE
Can't locate .svg icon in any nested page.

### ISSUE THREAD

**Issue by MacHu-GWU** [choldgraf/sphinx-copybutton#8]
![image](https://user-images.githubusercontent.com/6800411/47184423-9cd92900-d2f8-11e8-8214-498b496ba906.png)

https://github.com/choldgraf/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copybutton.js#L21

```
<img src="_static/copy-button.svg" alt="Copy to clipboard">
```

In nested page, it will search from the current directory. It should search from root domain.

I think this could solve the problem.

```
<img src="/_static/copy-button.svg" alt="Copy to clipboard">
```

**Comment by choldgraf** [comment]
blegh - I just noticed this today as well...good catch!

**Comment by MacHu-GWU** [comment]
@choldgraf I notice that you are manually creating virtualenv, testing it, and deploy it. I recommend you to use this tool https://github.com/MacHu-GWU/pygitrepo-project, to automate the tedious development operation.

```
$ make up # create virtualenv
$ make dev_install # setup dev env, install depends
$ make test # unit test
$ make build_doc # build doc
$ make view_doc # view doc
$ make publish # publish to pypi
```

**Comment by MacHu-GWU** [comment]
@choldgraf I don't think you should use CDN to server svg. because sphinx will copy the file to domain/_static/copy-botton.svg, serve from local definitely faster than any CDN.

Just use /_static/copy-button.svg is fine

**Comment by choldgraf** [comment]
@MacHu-GWU so I tried `/_static/copy-button.svg` and it was serving it from the base url, e.g. if the svg was here: `mysite.org/mysubsite/_static/copy-button.svg` the links would be rendered as `mysite.org/_static/copy-button.svg`.

Any idea how to get around that?

**Comment by xtianus** [comment]
Maybe you can get around this problem if you don't insert an <img> but a <div> with a background image relative to the css.
